name: cooki
description: "A new Flutter project."
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.1.0+2

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_riverpod: ^2.6.1
  flutter_dotenv: ^5.2.1
  dio: ^5.8.0+1
  cached_network_image: ^3.4.1
  mocktail: ^1.0.4
  cloud_firestore: ^5.6.7
  firebase_core: ^3.13.0
  google_sign_in: ^6.3.0
  firebase_auth: ^5.5.3
  firebase_crashlytics: ^4.3.5
  intl: ^0.19.0
  image_picker: ^1.1.0
  firebase_storage: ^12.4.5
  flutter_localizations:
    sdk: flutter
  url_launcher: ^6.3.1
  kakao_flutter_sdk_user: ^1.9.7+3
  cloud_functions: ^5.5.1
  firebase_ai: ^2.0.0
  flutter_image_compress: ^2.4.0
  easy_image_viewer: ^1.5.1
  path_provider: ^2.1.5
  share_plus: ^11.0.0
  package_info_plus: ^8.3.0
  sign_in_with_apple: ^7.0.1
  flutter_svg: ^2.2.0
  shared_preferences: ^2.5.3
  firebase_remote_config: ^5.4.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_native_splash: ^2.4.6

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - .env
    - assets/
    - assets/icons/
    - assets/prompts/
    - assets/prompts/ko/
    - assets/prompts/en/
    - assets/no_image.png

flutter_native_splash:
  color: "#1D8163"
  image: "assets/icons/cooki_logo_white.png"
  color_ios: "#1D8163"
